stp/api/urls.py
from django.urls import path, include
from .views import ProductoList, ProductoDetalle, \
    ClienteList

urlpatterns = [
    path('v1/productos/',ProductoList.as_view(),name='producto_list'),
    path('v1/productos/<str:codigo>',ProductoDetalle.as_view(),name='producto_detalle'),
    path('v1/clientes/',ClienteList.as_view(),name='cliente_list')
]

stp/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

print("PASO URL")
urlpatterns = [

    path('', include(('bases.urls', 'bases'), namespace='bases')),
    path('inv/', include(('inv.urls', 'inv'), namespace='inv')),
    path('cmp/', include(('cmp.urls', 'cmp'), namespace='cmp')),
    path('fac/', include(('fac.urls', 'fac'), namespace='fac')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stp/fullalm/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from .views import *
from .reportes import *


bases_urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('login/', auth_views.LoginView.as_view(template_name='bases/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='bases/login.html'), name='logout'),

    path('sin_privilegios/', HomeSinPrivilegios.as_view(), name='sin_privilegios'),

    path('idiomas/', IdiomaList.as_view(), name="idiomas"),
    path('frases/', FraseList.as_view(), name="frases"),
]


cmp_urlpatterns = [
    path('proveedores/', ProveedorView.as_view(), name="proveedor_list"),
    path('proveedores/new', ProveedorNew.as_view(), name="proveedor_new"),
    path('proveedores/edit/<int:pk>', ProveedorEdit.as_view(), name="proveedor_edit"),
    path('proveedores/inactivar/<int:id>', proveedorInactivar, name="proveedor_inactivar"),

    path('compras/', ComprasView.as_view(), name="compras_list"),
    path('compras/new', compras, name="compras_new"),
    path('compras/edit/<int:compra_id>', compras, name="compras_edit"),
    path('compras/<int:compra_id>/delete/<int:pk>', CompraDetDelete.as_view(), name="compras_del"),

    path('compras/listado', reporte_compras, name='compras_print_all'),
    path('compras/<int:compra_id>/imprimir', imprimir_compra, name="compras_print_one"),
]


fac_urlpatterns = [
    path('clientes/',ClienteView.as_view(), name="cliente_list"),
    path('clientes/new',ClienteNew.as_view(), name="cliente_new"),
    path('clientes/<int:pk>',ClienteEdit.as_view(), name="cliente_edit"),
    path('clientes/estado/<int:id>',clienteInactivar, name="cliente_inactivar"),

    path('facturas/',FacturaView.as_view(), name="factura_list"),
    path('facturas/new',facturas, name="factura_new"),
    path('facturas/edit/<int:id>',facturas, name="factura_edit"),

    path('facturas/buscar-producto',ProductoView.as_view(), name="factura_producto"),

    path('facturas/borrar-detalle/<int:id>',borrar_detalle_factura, name="factura_borrar_detalle"),

    path('facturas/imprimir/<int:id>',imprimir_factura_recibo, name="factura_imprimir_one"),

    path('facturas/imprimir-todas/<str:f1>/<str:f2>',imprimir_factura_list, name="factura_imprimir_all"),

    path('facturas/clientes/new/',cliente_add_modify,name="fac_cliente_add"),
    path('facturas/clientes/<int:pk>',cliente_add_modify,name="fac_cliente_mod"),
]


inv_urlpatterns = [
    path('categorias/', CategoriaView.as_view(), name='categoria_list'),
    path('categorias/new', CategoriaNew.as_view(), name='categoria_new'),
    path('categorias/edit/<int:pk>', CategoriaEdit.as_view(), name='categoria_edit'),
    path('categorias/delete/<int:pk>', CategoriaDel.as_view(), name='categoria_del'),

    path('subcategorias/', SubCategoriaView.as_view(), name='subcategoria_list'),
    path('subcategorias/new', SubCategoriaNew.as_view(), name='subcategoria_new'),
    path('subcategorias/edit/<int:pk>', SubCategoriaEdit.as_view(), name='subcategoria_edit'),
    path('subcategorias/delete/<int:pk>', SubCategoriaDel.as_view(), name='subcategoria_del'),

    path('marcas/', MarcaView.as_view(), name="marca_list"),
    path('marcas/new', MarcaNew.as_view(), name="marca_new"),
    path('marcas/edit/<int:pk>', MarcaEdit.as_view(), name="marca_edit"),
    path('marcas/inactivar/<int:id>', marca_inactivar, name="marca_inactivar"),

    path('um/', UMView.as_view(), name="um_list"),
    path('um/new', UMNew.as_view(), name="um_new"),
    path('um/edit/<int:pk>', UMEdit.as_view(), name="um_edit"),
    path('um/inactivar/<int:id>', um_inactivar, name="um_inactivar"),

    path('productos/', ProductoView.as_view(), name="producto_list"),
    path('productos/new', ProductoNew.as_view(), name="producto_new"),
    path('productos/edit/<int:pk>', ProductoEdit.as_view(), name="producto_edit"),
    path('productos/inactivar/<int:id>', producto_inactivar, name="producto_inactivar"),
]

stp/fullalm/models.py
from django.db import models

# ------>  Importando para BASES
from django.contrib.auth.models import User
# from django_userforeignkey.models.fields import UserForeignKey

# ------> Importando para [CMP, FAC]
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.db.models import Sum


# *********************************************************************
# *                        MODELS FROM BASES                          *
# *********************************************************************

class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    um = models.IntegerField(blank=True,null=True)

    class Meta:
        abstract = True


class ClaseModelo2(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    uc = models.ForeignKey(User, on_delete=models.CASCADE)
    # um = models.IntegerField(blank=True,null=True)
    # uc = UserForeignKey(auto_user_add=True,related_name='+')
    # um = UserForeignKey(auto_user=True,related_name='+')

    class Meta:
        abstract = True


class Idioma(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50)

    class Meta:
        verbose_name_plural = "Idiomas"

    def __str__(self):
        return self.nombre


class Frase(models.Model):
    id = models.AutoField(primary_key=True)
    idioma = models.ForeignKey(Idioma, on_delete=models.CASCADE)
    autor = models.CharField(max_length=50,default="Anónimo")
    frase = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name_plural = "Frases"

    def __str__(self):
        return "{} - {}".format(self.autor,self.idioma)


# *********************************************************************
# *                          MODELS FROM INV                          *
# *********************************************************************


class Categoria(ClaseModelo):
    id = models.AutoField(primary_key=True)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Categoría',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Categoria, self).save()

    class Meta:
        verbose_name_plural = "Categorias"


class SubCategoria(ClaseModelo):
    id = models.AutoField(primary_key=True)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Categoría'
    )

    def __str__(self):
        return '{}:{}'.format(self.categoria.descripcion, self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(SubCategoria, self).save()

    class Meta:
        verbose_name_plural = "Sub Categorias"
        unique_together = ('categoria', 'descripcion')


class Marca(ClaseModelo):
    id = models.AutoField(primary_key=True)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Marca',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Marca, self).save()

    class Meta:
        verbose_name_plural = "Marca"


class UnidadMedida(ClaseModelo):
    id = models.AutoField(primary_key=True)
    descripcion = models.CharField(
        max_length=100,
        help_text='Descripción de la Unidad Medida',
        unique=True
    )

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(UnidadMedida, self).save()

    class Meta:
        verbose_name_plural = "Unidades de Medida"


class Producto(ClaseModelo):
    id = models.AutoField(primary_key=True)
    codigo = models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)
    precio = models.FloatField(default=0)
    existencia = models.IntegerField(default=0)
    ultima_compra = models.DateField(null=True, blank=True)

    marca = models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida = models.ForeignKey(UnidadMedida, on_delete=models.CASCADE)
    subcategoria = models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to="images/", null=True, blank=True)

    def __str__(self):
        return '{}'.format(self.descripcion)

    def save(self):
        self.descripcion = self.descripcion.upper()
        super(Producto, self).save()

    class Meta:
        verbose_name_plural = "Productos"
        unique_together = ('codigo', 'codigo_barra')


class AsMotivos(ClaseModelo):
    idmot = models.AutoField(db_column='IDMOT', primary_key=True)  # Field name made lowercase.
    codarea = models.IntegerField(db_column='CODAREA', blank=True, null=True)  # Field name made lowercase.
    codmot = models.IntegerField(db_column='CODMOT', blank=True, null=True)  # Field name made lowercase.
    desmotivo = models.CharField(db_column='DESMOTIVO', max_length=70, blank=True,
                                 null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'AS_Motivos'


class Archivoinformebaja(ClaseModelo):
    item = models.AutoField(db_column='Item', primary_key=True)  # Field name made lowercase.
    nrosolling = models.BigIntegerField(db_column='Nrosolling')  # Field name made lowercase.
    archivo = models.BinaryField(db_column='Archivo', blank=True, null=True)  # Field name made lowercase.
    fecpro = models.DateTimeField(db_column='FecPro', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ArchivoInformeBaja'


class Califica(ClaseModelo):
    item = models.AutoField(primary_key=True)
    descripcion = models.CharField(db_column='Descripcion', max_length=100, blank=True, null=True)  # Field name made lowercase.
    estado = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Califica'


class Cecofinal(ClaseModelo):
    id = models.FloatField(db_column='ID', blank=True, null=False, primary_key=True)  # Field name made lowercase.
    descripcion = models.CharField(db_column='Descripcion', max_length=255, blank=True, null=True)  # Field name made lowercase.
    cecos = models.CharField(db_column='CECOS', max_length=255, blank=True, null=True)  # Field name made lowercase.
    depend = models.FloatField(db_column='DEPEND', blank=True, null=True)  # Field name made lowercase.
    cebes = models.CharField(db_column='CEBES', max_length=255, blank=True, null=True)  # Field name made lowercase.
    ceges = models.CharField(db_column='CEGES', max_length=255, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'CecoFINAL'


class Contratoorden(ClaseModelo):
    item = models.AutoField(primary_key=True)
    idcontrato = models.IntegerField(blank=True, null=True)
    orden = models.CharField(max_length=50, blank=True, null=True)
    estado = models.CharField(max_length=1, blank=True, null=True)
    cuenta = models.CharField(max_length=1, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'ContratoOrden'


class Destino(ClaseModelo):
    coddes = models.IntegerField(db_column='CodDes', blank=True, null=False, primary_key=True)  # Field name made lowercase.
    desdestino = models.CharField(db_column='DesDestino', max_length=50, blank=True, null=True)  # Field name made lowercase.
    estado = models.CharField(db_column='Estado', max_length=1, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Destino'


class Imaterial(ClaseModelo):
    idcod = models.BigIntegerField(db_column='IdCod', blank=True, null=False, primary_key=True)  # Field name made lowercase.
    bukrs = models.CharField(db_column='BUKRS', max_length=4, blank=True, null=True)  # Field name made lowercase.
    mjahr = models.IntegerField(db_column='MJAHR', blank=True, null=True)  # Field name made lowercase.
    werks = models.CharField(db_column='WERKS', max_length=4, blank=True, null=True)  # Field name made lowercase.
    lgort = models.CharField(db_column='LGORT', max_length=4, blank=True, null=True)  # Field name made lowercase.
    bwart = models.CharField(db_column='BWART', max_length=3, blank=True,null=True)  # Field name made lowercase.
    mblnr = models.CharField(db_column='MBLNR', max_length=10, blank=True, null=True)  # Field name made lowercase.
    zeile = models.IntegerField(db_column='ZEILE', blank=True, null=True)  # Field name made lowercase.
    budat = models.CharField(db_column='BUDAT', max_length=8, blank=True, null=True)  # Field name made lowercase.
    usnam = models.CharField(db_column='USNAM', max_length=12, blank=True, null=True)  # Field name made lowercase.
    matnr = models.CharField(db_column='MATNR', max_length=18, blank=True, null=True)  # Field name made lowercase.
    maktx = models.CharField(db_column='MAKTX', max_length=40, blank=True, null=True)  # Field name made lowercase.
    erfmg = models.DecimalField(db_column='ERFMG', max_digits=13, decimal_places=3, blank=True, null=True)  # Field name made lowercase.
    erfme = models.CharField(db_column='ERFME', max_length=3, blank=True, null=True)  # Field name made lowercase.

stp/fullalm/templates/categoria_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Categoría
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col-10">
                            <div class="input-group">
                                <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción"
                                value="{% if obj %} {{ obj.descripcion }} {% endif %}">
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="form-group">
                                <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                {% if obj.estado %} checked {% endif %} >
                            </div>
                        </div> 
                        <!-- {{ form.as_p }} -->
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'inv:categoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock %}

stp/fullalm/templates/compras_list.html
{% extends 'base/base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de Proveedor</h6>
    <div class="dropdown no-arrow">
      <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
        <div class="dropdown-header">Acciones:</div>
        <a class="dropdown-item" href="{% url 'cmp:compras_new' %}"><i class="far fa-calendar-plus"></i> Nueva</a>
        <a class="dropdown-item" href="{% url 'cmp:compras_print_all' %}" target="reportes"><i class="fas fa-print"></i> Listado</a>
      </div>
    </div>
  </div>
  <!-- Card Body -->
  <div class="card-body">
    {% if not obj %}
    <div class="alert alert-info">No hay compras</div>
    {% endif %}
    <table class="table table-striped table-hover dt-responsive nowrap" style="width:100%">
      <thead>
        <th>Id</th>        
        <th>Fecha</th>
        <th>Observación</th>
        <th>No. Factura</th>
        <th>F. Factura</th>
        <th>Sub Total</th>
        <th>Descuento</th>
        <th>Total</th>
        <th>Estado</th>
        <th class="all">Acciones</th>
      </thead>
      <tbody>
        {% for item in obj%}
        <tr>
          <td>{{ item.id }}</td>
          <td>{{ item.fecha_compra }}</td>
          <td>{{item.observacion}}</td>
          <td>{{ item.no_factura }}</td>
          <td>{{ item.fecha_factura }}</td>
          <td>{{ item.sub_total }}</td>
          <td>{{ item.descuento }}</td>
          <td>{{ item.total }}</td>
          <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
          <td>
            <a class="btn btn-warning btn-circle" href="{% url 'cmp:compras_edit' item.id %}"><i class="far fa-edit"></i></a>
            <a class="btn btn-success btn-circle" href="{% url 'cmp:compras_print_one' item.id %}" target="reportes"><i class="fas fa-print"></i></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>
// Call the dataTables jQuery plugin
$(document).ready(function() {
  $('.table').DataTable({
    "language": {
      "sProcessing": "Procesando...",
      "sLengthMenu": "Mostrar _MENU_ registros",
      "sZeroRecords": "No se encontraron resultados",
      "sEmptyTable": "Ningún dato disponible en esta tabla",
      "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
      "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
      "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
      "sInfoPostFix": "",
      "sSearch": "Buscar:",
      "sUrl": "",
      "sInfoThousands": ",",
      "sLoadingRecords": "Cargando...",
      "oPaginate": {
          "sFirst": "<span class='fa fa-angle-double-left'></span>",
          "sLast": "<span class='fa fa-angle-double-right'></span>",
          "sNext": "<span class='fa fa-angle-right'></span>",
          "sPrevious": "<span class='fa fa-angle-left'></span>"
      },
      "oAria": {
          "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
          "sSortDescending": ": Activar para ordenar la columna de manera descendente"
      }
    }
  });
});
</script>
{% endblock %}

stp/fullalm/templates/producto_form.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inv:producto_edit' obj.pk %}" enctype="multipart/form-data" >
        {% else %}
        <form method="POST" role="form" class="form-inline" action="{% url 'inv:producto_new' %}"  enctype="multipart/form-data" >
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nuevo {% endif %} Producto
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {#{ form.as_p }#}
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">{{form.codigo.label}}</div>
                                <div class="col-md-6">{{form.codigo}}</div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-6">{{form.codigo_barra.label}}</div>
                                <div class="col-md-6">{{form.codigo_barra}}</div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">{{form.descripcion.label}}</div>
                                <div class="col-md-6">{{form.descripcion}}</div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-6">{{form.precio.label}}</div>
                                <div class="col-md-6">{{form.precio}}</div>
                            </div>

                        </div>
                        
                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">{{form.existencia.label}}</div>
                                <div class="col-md-6">{{form.existencia}}</div>    
                            </div>

                            <div class="col-md-4">
                                <div class="col-md-8">{{form.ultima_compra.label}}</div>
                                <div class="col-md-6">{{form.ultima_compra}}</div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">{{form.marca.label}}</div>
                                <div class="col-md-6">{{form.marca}}</div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-8">{{form.unidad_medida.label}}</div>
                                <div class="col-md-6">{{form.unidad_medida}}</div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">Categoría</div>
                                <div class="col-md-6">
                                    <!--<select name="categoria" id="id_categoria" class="form-control form-control-sm">-->
                                    <select name="categoria" id="categoria" class="form-control">
                                        <option value="0">---------</option>
                                        {% for item in categorias %}
                                        <option value="{{item.id}}">{{item.descripcion}}</option>
                                        {% endfor%}
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="col-md-6">Sub Categoría</div>
                                <div class="col-md-6">
                                    <!--<select name="subcategoria" id="id_subcategoria" class="form-control form-control-sm">-->
                                    <select name="subcategoria" id="subcategoria" class="form-control">
                                        <option value="0">---------</option>
                                        {% for item in subcategorias %}
                                        <option value="{{item.id}}" data-chained="{{item.categoria.id}}">{{item.descripcion}} </option>
                                        {% endfor%}
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="col-md-6">{{form.estado.label}}</div>
                                <div class="col-md-6">{{form.estado}}</div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-2">
                                    {{form.foto.label}}
                                </div>
                                <div class="col-md-8">
                                    {% if obj.foto %}
                                    <img src="{{obj.foto.url}}" width="100%" alt="">
                                    {% endif %}
                                </div>
                                <!-- <div class="col-md-4">{{form.foto}}</div> -->
                                <div class="col-md-2">
                                    <input type="file" name="foto" id="id_foto" accept="image/*">
                                </div>
                            </div>
                        </div>

                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <!-- <a href="{% url 'inv:um_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a> -->
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                    Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="far fa-calendar-plus fa-2x text-gray-300"></i>
                    </div>
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div>

<script>
    $(function() {
        $("#id_categoria").val("{{ obj.subcategoria.categoria.id }}").change();
        $("#id_subcategoria").val("{{ obj.subcategoria.id }}").change();
        $("#id_subcategoria").chained("#id_categoria");
    });
</script>

stp/fullalm/templates/subcategoria_form.html
{% extends 'base/base.html' %}

{% block page_content %}
<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-12 col-md-12 mb-12">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Sub Categoría
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col-5">
                            <div class="input-group">
                                <!-- <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción"
                                value="{% if obj %} {{ obj.descripcion }} {% endif %}"> -->
                                {{ form.categoria }}
                            </div>
                        </div>
                        <div class="col-5">
                            <div class="input-group">
                                <!-- <input type="text" name="descripcion" maxlength="100" class="form-control" required id="id_descripcion" placeholder="Descripción"
                                value="{% if obj %} {{ obj.descripcion }} {% endif %}"> -->
                                {{ form.descripcion }}
                            </div>
                        </div>
                        <div class="col-2">
                            <div class="input-group">
                                <!-- <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                {% if obj.estado %} checked {% endif %} > -->
                                {{ form.estado }}
                            </div>
                        </div> 
                        <!-- {{ form.as_p }} -->
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'inv:subcategoria_list' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}
{% block js_page %}
{% endblock %}